version: "3.6"

services:
    nginx:
        build:
            context: ./nginx
        image: ${CURRENT_NGINX_IMG}
        ports:
            - ${HOST_HTTP_PORT}:80
        volumes:
            - ${HOST_ROOT}:${CONTAINER_ROOT}
        networks:
            - bx-net

    mysql:
        build:
            context: ./mysql
        image: ${CURRENT_DB_IMG}
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${HOST_DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - bx-net

networks:
    bx-net:
        driver: bridge
