version: "3.6"

services:
    php:
        build:
            context: ./php
        image: ${CURRENT_PHP_IMG}
        ports:
            - 9000:9000
        volumes:
            - ${HOST_ROOT}:${CONTAINER_ROOT}
        working_dir: ${CONTAINER_ROOT}
        environment:
            XDEBUG_CONFIG: "remote_host=docker.for.mac.host.internal remote_port=9001"
            PHP_IDE_CONFIG: "serverName=APN-demo"
        tty: true
        networks:
            - bx-net
